name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - name: generate
        uses: Platane/snk@v3
        with:
          github_user_name: XCHAUDHARY00
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: push
        run: |
          cd dist
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
          git switch --orphan output
          git add -A
          git commit -m "chore: generate snake"
          git push -f origin output
